version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bios
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/entrypoint.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_data:/var/lib/mysql

volumes:
  db_data:
